* CVE-2021-26084
--------
** Description
    - POC of CVE-2021-26084, which is Atlassian Confluence Server OGNL(Object-Graph Navigation Language) Pre-Auth RCE Injection Vulneralibity.
    - create by antx at 2022-01-13.
--------
** Detail
    - In affected versions of Confluence Server and Data Center, an OGNL injection vulnerability exists that would allow an authenticated user, and in some instances an unauthenticated user, to execute arbitrary code on a Confluence Server or Data Center instance. The vulnerable endpoints can be accessed by a non-administrator user or unauthenticated user if ‘Allow people to sign up to create their account’ is enabled. To check whether this is enabled go to COG > User Management > User Signup Options.
--------
** CVE Severity
    - attackComplexity: LOW
    - attackVector: NETWORK
    - availabilityImpact: HIGH
    - confidentialityImpact: HIGH
    - integrityImpact: HIGH
    - privilegesRequired: NONE
    - scope: UNCHANGED
    - userInteraction: NONE
    - version: 3.1
    - baseScore: 9.8
    - baseSeverity: CRITICAL
--------
** Affect
    - The affected versions are before version 6.13.23, from version 6.14.0 before 7.4.11, from version 7.5.0 before 7.11.6, and from version 7.12.0 before 7.12.5.
--------
** POC
    - [[./CVE-2021-26084.py][Poc]]
--------
** Reference
    - Ref-Source
        - [[https://github.com/httpvoid/writeups/blob/main/Confluence-RCE.md]]
        - [[https://github.com/r0ckysec/CVE-2021-26084_Confluence]]
        - [[https://github.com/h3v0x/CVE-2021-26084_Confluence]]
        - [[https://github.com/dorkerdevil/CVE-2021-26084]]
        - [[https://github.com/ycdxsb/PocOrExp_in_Github/blob/main/2021/README.md]]
    - Ref-Risk
        - [[https://nvd.nist.gov/vuln/detail/CVE-2021-26084][NVD<CVE-2021-26084>]]
    - CVE
        - [[https://github.com/CVEProject/cvelist/blob/master/2021/26xxx/CVE-2021-26084.json][CVE-2021-26084]]
* IMPORTANT
    - This exploit is only intended to facilitate demonstrations of the vulnerability by researchers. I disapprove of illegal actions and take no responsibility for any malicious use of this script. The proof of concept demonstrated in this repository does not expose any hosts and was performed with permission.
